# Defaults file role ansible-nginx
---

  config_nginx: true

  nginx_config_workerprocesses: auto

  nginx_config_workerconnections: 768

  nginx_config_keepalivetimeout: 61

  nginx_config_main_file: true

  nginx_listen_port: 80

  nginx_virtualhost_add: true

  # defines setting added to /etc/nginx/site-avalible/vhost.conf
  vhost_server_name: "dev.local"
  nginx_vhostadd_block:
    - server_name: "{{ vhost_server_name }}"
      default_server: false
      index:
        - index.html
        - index.htm
        - index.php
      listen_address: "*"
      listen_port: "{{ nginx_listen_port }}"
      location: /
      root: /var/www/dev.local
      try_files: "$uri $uri/ =404"
