---

  - name: config_nginx | {{ ansible_os_family }} | copy port.conf
    template:
      src: etc/nginx2/ports.conf.j2
      dest: /etc/nginx2/ports.conf
    become: true
    when: ansible_os_family == "Debian"

  - name: config_nginx | {{ ansible_os_family }} | add virtualhost folder
    file:
      path: "{{ item.documentroot }}"
      state: "directory"
      owner: "{{ nginx_web_owner }}"
      group: "{{ nginx_web_group }}"
    become: true
    with_items: '{{ nginx_virtualhosts }}'
    when: nginx_vhost_add

  - name: config_nginx | {{ ansible_os_family }} |add virtualhost custome file
    template:
      src: "{{ nginx_vhost_folder_src }}/vhost.conf.j2"
      dest: "{{ nginx_vhost_folder_dest }}/vhost.conf"
    become: true
    notify:
      - restart nginx
    when: (nginx_vhost_add and ansible_os_family == "Debian") or (nginx_vhost_add and ansible_os_family == "RedHat")
