---

  - name: config_apache | {{ ansible_os_family }} | copy port.conf
    template:
      src: etc/apache2/ports.conf.j2
      dest: /etc/apache2/ports.conf
    become: true
    when: ansible_os_family == "Debian"

  - name: config_apache | {{ ansible_os_family }} | add virtualhost folder
    file:
      path: "{{ item.documentroot }}"
      state: "directory"
      owner: "{{ apache_web_owner }}"
      group: "{{ apache_web_group }}"
    become: true
    with_items: '{{ apache_virtualhosts }}'
    when: apache_vhost_add

  - name: config_apache | {{ ansible_os_family }} |add virtualhost custome file
    template:
      src: "{{ apache_vhost_folder_src }}/vhost.conf.j2"
      dest: "{{ apache_vhost_folder_dest }}/vhost.conf"
    become: true
    notify:
      - restart apache
    when: (apache_vhost_add and ansible_os_family == "Debian") or (apache_vhost_add and ansible_os_family == "RedHat")
