---
  - name: {{ ansible_os_family }} | yum update cache
    yum:
      update_cache: yes
    become: true

  - name: {{ ansible_os_family }} | install httpd
    yum: "name={{ redhat_package }} state=present"
    become: true

  - name: {{ ansible_os_family }} |

  - name: {{ ansible_os_family }} | enable service httpd
    service:
      name: httpd
      state: started
      enabled: yes
    become: true
