---
  - name: Setting Debian facts
    set_fact:
      apache2_log_dir: "/var/log/apache2"
      apache2_web_group: "www-data"
      apache2_web_owner: "www-data"
      apache2_web_root: "/var/www/html"
      apache2_vhost_folder_src: "etc/apache2/sites-available"
      apache2_vhost_folder_dest: "/etc/apache2/sites-available"
    when: ansible_os_family == "Debian"

  - name: Setting RedHat facts
    set_fact:
      apache2_log_dir: "/var/log/httpd"
      apache2_web_group: "apache"
      apche2_web_owner: "apache"
      apache2_web_root: "/var/www/html"
    when: ansible_os_family == "RedHat"
