---
  # handlers file
  - name: restart nginx
    service:
      name: "{{ nginx_service_name }}"
      state: "{{ nginx_service_restarted }}"
    become: true

  - name: reload nginx
    service:
      name: "{{ nginx_service_name }}"
      state: "{{ nginx_service_reload }}"
    become: true
