---
  # handlers file
  - name: restart apache2
    service:
      name: "{{ apache_service_name }}"
      state: "{{ apache_service_restarted }}"
    become: true

  - name: reload apache2
    service:
      name: "{{ apache_service_name }}"
      state: "{{ apache_service_reload }}"
    become: true
