---
  - name: Setting Debian facts
    set_fact:
      nginx_log_dir: "/var/log/nginx"
      nginx_service_user: www-data
      nginx_service_group: www-data
      nginx_web_root: "/var/www"
    when: ansible_os_family == "Debian"

  - name: Setting RedHat facts
    set_fact:
      nginx_log_dir: "/var/log/nginx"
      nginx_service_group: "nginx"
      nginx_service_user: "nginx"
      nginx_web_root: "/usr/share/nginx/"
    when: ansible_os_family == "RedHat"
