---
  - name: Setting Debian facts
    set_fact:
      apache_log_dir: "/var/log/"
      apache_service_name:
      apache_vhost_folder_src: "etc/"
      apache_vhost_folder_dest: "/etc/"
      apache_web_group: " "
      apache_web_owner: " "
      apache_web_root: "/var/www/"
    when: ansible_os_family == "Debian"

  - name: Setting RedHat facts
    set_fact:
      apache_log_dir: "/var/log/"
      apache_service_name:
      apache_vhost_folder_src: "etc/"
      apache_vhost_folder_dest: "/etc/"
      apache_web_group: " "
      apache_web_owner: " "
      apache_web_root: "/var/www/"
    when: ansible_os_family == "RedHat"
